config/routes.rb
Ujala::Application.routes.draw do
    resources :workers
    root :to => 'workers#index'

end

# end

app/models/worker.rb
class Worker < ActiveRecord::Base
  attr_accessible :age, :name, :num_of_ratings, :rating, :skills
  def self.all_skills
    %w(Teacher Driver Cook Dancer Painter)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/worker_controller.rb
class WorkerController < ApplicationController
  def index
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
	def new
    @all_skills = Worker.all_skills
    # default: render 'new' template
  	end
  	def index
  		@all_workers = Worker.all
  	end

  	def edit
      @all_skills = Worker.all_skills
      @worker = Worker.find params[:id]
      @my_skills = @worker[:skills]
  	end

  	def update
      abc = ""
      params[:skills].each do |key, value|
        abc = abc + "," + key
      end
      abc[0] = ''
    	@worker = Worker.find params[:id]
    	@worker.update_attributes!(params[:worker])
      abc
      @worker.update_attributes!(:skills => abc)
      if @selected_skills == {}
      @selected_skills = Hash[@all_skills.map {|skill| [skill, skill]}]
    end
    	flash[:notice] = "Information of #{@worker.name} was successfully updated."
    	redirect_to workers_path(@worker)
  end

  	def destroy
      @worker = Worker.find(params[:id])
      @worker.destroy
      flash[:notice] = "Worker '#{@worker.name}' deleted."
      redirect_to workers_path
  	end 

  	def show
	    id = params[:id] # retrieve movie ID from URI route
	    @Worker = Worker.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  	end
	def create
      abc = ""
      params[:skills].each do |key, value|
        abc = abc + "," + key
      end
      abc[0] = ''

    	@Worker = Worker.create!(params[:worker])
      @Worker.update_attributes!(:skills => abc)
      # update_attributes!
      Rails.logger.warn "LOLLLOLOL \n\n\n"
      Rails.logger.warn  abc

    	flash[:notice] = "#{@Worker.name} was successfully created."
   		redirect_to workers_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worker_helper.rb
module WorkerHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ujala</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/worker/index.html.haml
%h1 Worker#index
%p Find me in app/views/worker/index.html.haml

app/views/workers/edit.html.haml
-# in app/views/movies/edit.html.haml
%h1 Edit Worker Information

= form_tag worker_path(@worker), :method => :put do

  = label :worker, :name, 'Name'
  = text_field :worker, 'name'

  = label :worker, :skills, 'Skills'
  Include: 
  - @all_skills.each do |r|
    = r
    - if (@my_skills.include? r)
      = check_box_tag "skills[#{r}]", value =1, checked = true, :id => "skills_#{r}"
    - else
      =  check_box_tag "skills[#{r}]", value =1, checked = false, :id => "skills_#{r}"
  
  = label :worker, :age, 'Age'
  = text_field :worker, 'age'

  = submit_tag 'Save Changes', :id => "Save Changes"

app/views/workers/index.html.haml
%h1 All Workers

%table#workers
  %thead
    %tr
      %th Name
      %th Age
      %th Skills
  %tbody
    - @all_workers.each do |work|
      %tr
        %td= work.name
        %td= work.age
        %td= work.skills
        %td= link_to "More about #{work.name}", worker_path(work)

= link_to 'Add new worker', new_worker_path, :id => 'Add_new_worker'

app/views/workers/new.html.haml
%h1 Create New Worker

= form_tag workers_path do

  = label :worker, :name, 'Name'
  = text_field :worker, 'name'

  = label :worker, :skills, 'Skills'
  Include: 
  - @all_skills.each do |r|
    = r
    = check_box_tag "skills[#{r}]",value =1, checked = false, :id => "skills_#{r}"

  = label :worker, :age, 'Age'
  = text_field :worker, 'age'

  = submit_tag 'Save Changes', :id => "Save Changes"

app/views/workers/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@Worker.name}

%ul#details
  %li
    Skills:
    = @Worker.skills
  %li
    Age:
    = @Worker.age

%h3 Description:

/ %p#description= @movie.description

= link_to 'Edit', edit_worker_path(@Worker)
= button_to 'Delete', worker_path(@Worker), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', worker_path